---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - cd frontend
  - npm config set spin false

install:
  - npm install -g ember-cli

script:
  - cd frontend
  - ember test
  - cd ../manager_features
  - rspec spec
