sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
env:
    - EMBER_VERSION=default

before_install:
    - cd frontend
    - "npm config set spin false"
    - "npm install -g npm@^4"
install:
    - npm install
script:
    - ember test